### ISSUE TITLE
Exception when calling read_handler: Monitor has no attribute 'multi' 

### ISSUE THREAD

**Issue by koen-venly** [DataDog/datadog-cloudformation-resources#303]
**Describe the bug**
Since today (16/04/2024) my monitors in cloudformation won't deploy anymore due to:

`Resource handler returned message: "Exception when calling read_handler: Monitor has no attribute 'multi' at ['['received_data']']['multi']" (RequestToken: 43ba9de6-ae3a-4d27-cae4-70f8e97ad464, HandlerErrorCode: null)
`

**To Reproduce**
Roll out following cloudformation snippet:

```
DatadogElb5xxMonitor:
    Type: "Datadog::Monitors::Monitor"
    Properties:
      Message: !Sub "HTTP 5xx Errors Alert for ${ProjectName} ${Environment} @slack-dd-elb-alerts"
      Name: !Sub "ELB - HTTP 5xx Errors Monitor ${ProjectName} ${Environment}"
      Tags:
        - !Sub "env:${Environment}"
        - !Sub "service:${DatadogServiceName}"
        - !Sub "projectname:${ProjectName}"
      Type: query alert
      Query: !Sub |
        sum(last_1h):sum:aws.applicationelb.httpcode_elb_5xx{projectname:${ProjectName}, environment:${Environment}} by {applicationname}.as_count() > 50
      Options:
        EvaluationDelay: 900
        IncludeTags: true
        NewGroupDelay: 60
        NotifyAudit: false
        NotifyNoData: false
        RenotifyInterval: 0
        RequireFullWindow: false
        Thresholds:
          Critical: 50
          CriticalRecovery: 49
          Warning: 30
          WarningRecovery: 29
        TimeoutH: 1
```

**Logs**
Resource handler returned message: "Exception when calling read_handler: Monitor has no attribute 'multi' at ['['received_data']']['multi']" (RequestToken: 43ba9de6-ae3a-4d27-cae4-70f8e97ad464, HandlerErrorCode: null)

**Expected behavior**
It rolls out like it always did before

**Screenshots**
![image](https://github.com/DataDog/datadog-cloudformation-resources/assets/98314170/0824921d-ac86-4fe7-ab50-3a6bc958e4dc)

**Environment and Versions (please complete the following information):**
Datadog Monitor 4.7.1

**Additional context**
It has always worked. More then a year, never had any issues

**Comment by pepitoenpeligro** [comment]
Hi team, any news here?

**Comment by ovidiu-dan-cepsachemicals** [comment]
Happens the same to us, the extension version 4.5.0 stopped working today (HandlerErrorCode: InternalFailure) and today trying to update to 4.7.1 got the multi error

**Comment by MarckFp** [comment]
Hi everyone!! We just had this same issue on our end. Investigating a little bit further I discovered the Cloudformation after creating a monitor it expects the parameter "multi" to be returned by DataDog API.

As we can see in this image

![image](https://github.com/DataDog/datadog-cloudformation-resources/assets/33698618/31e965ba-71c1-497c-b15a-1ebb4f0a2e29)

In fact [DataDog API Documentation](https://docs.datadoghq.com/api/latest/monitors/#create-a-monitor) says that exact parameter is returned by their API like you can see in the image:

![image](https://github.com/DataDog/datadog-cloudformation-resources/assets/33698618/5f808516-1ad8-46f4-8855-440d4f1fd97b)
 

However it doesn't return that value when a new monitor is created (tested in Insomnia and Postman), that's why we receive that error. I already opened a ticket to DataDog Support but in the meantime we can still deploy monitors using:

`cdk deploy DataDog-Monitor --no-rollback`

**Comment by pepitoenpeligro** [comment]
In the solution proposed by @MarckFp , deploying a Cloudformation template with 
 - `aws cloudformation create-stack --stack-name MYSTACK --template-body file://MYTEMPLATE.json --disable-rollback`
- `cdk deploy -e my-stack --no-rollback` 

creates the datadog monitor as well and can be viewed in the Datadog portal, but the CF stack is still receiving the error. 

Thanks to @MarckFp for providing this workaround.

**Comment by pepitoenpeligro** [comment]
Update: magically, now "05:18" UTC / 07:18 Spain it works 

![image](https://github.com/DataDog/datadog-cloudformation-resources/assets/14912971/83ed27b4-9bbf-45b9-8fb8-c7af03a1f8db)

**Comment by skarimo** [comment]
Thanks for opening the issue. We have identified the issue and put a fix in place. I am going to go ahead and close this issue but feel free to follow up if you have further questions.
