### ISSUE TITLE
Feature: Return External ID as param within AWS Integration resource

### ISSUE THREAD

**Issue by allistera** [DataDog/datadog-cloudformation-resources#71]
Hi,

It is vital to providing an end-to-end cloudformation template for integrating into Datadog that the 'Datadog::Integrations::AWS' type returns External ID.

I don't seem to have permission to access the datadog-api-client-java library or else I would have opened a PR to add this in... I guess I could still open one but would need Datadog folk to test it. 

Thanks

**Comment by jamesrenaud** [comment]
+1 on this (also to unmark it as stale).

Without being able to get the external ID that's generated to create the role, this integration is unusable.

**Comment by mpratsch** [comment]
> +1 on this (also to unmark it as stale).
> 
> Without being able to get the external ID that's generated to create the role, this integration is unusable.

+1 same here. I've build a workaround but because of that it's not easily possible to implement that to our 100% build cloudformation infrastructure code so we have to run it manually. ☹

**Comment by joyhumin** [comment]
+1 same here. It looks like without external ID returned from the registry will introduce vulnerability. We haven't adopt the registry due to potential confused deputy problem and AWS recommend the best practice with external ID as well [AWS doc](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html). Hope this will add in future version.
